job_keywords = {
    "ai/ml engineer": ["python", "machine learning", "tensorflow", "pytorch", "deep learning", "scikit-learn", "data science", "nlp", "opencv", "reinforcement learning", "model deployment", "artificial intelligence"],
    "ar/vr developer": ["unity", "unreal engine", "augmented reality", "virtual reality", "3d modeling", "blender", "c#", "vr headsets", "oculus", "htc vive", "vuforia", "arcore"],
    "advocate": ["legal", "law", "case", "litigation", "drafting", "court", "contracts", "compliance", "negotiation", "legal research", "intellectual property", "civil law"],
    "android/ios developer": ["android", "ios", "kotlin", "swift", "mobile development", "flutter", "react native", "xcode", "java", "objective-c", "android studio", "firebase"],
    "arts": ["painting", "sculpture", "design", "drawing", "visual arts", "illustration", "fine arts", "digital painting", "art history", "portrait", "graphic design", "watercolor"],
    "automation testing": ["selenium", "automation", "test scripts", "pytest", "testng", "robot framework", "ci/cd", "jenkins", "java", "test case", "bug tracking", "unit testing"],
    "blockchain": ["blockchain", "cryptocurrency", "ethereum", "smart contract", "solidity", "web3", "nfts", "defi", "bitcoin", "crypto wallet", "dapps", "decentralized finance"],
    "blockchain developer": ["solidity", "ethereum", "dapps", "smart contract", "hyperledger", "ganache", "truffle", "web3.js", "ipfs", "bsc", "ethereum 2.0", "erc-20"],
    "business analyst": ["business analysis", "requirement gathering", "data analysis", "stakeholders", "user stories", "agile", "jira", "business process modeling", "sprint planning", "use case", "data mapping", "project documentation"],
    "business intelligence analyst": ["power bi", "tableau", "data visualization", "sql", "dashboard", "business objects", "data mining", "etl", "business analysis", "data reporting", "dax", "data wrangling"],
    "civil engineer": ["autocad", "construction", "site engineer", "project management", "structural", "estimation", "civil design", "surveying", "building materials", "site planning", "road construction", "steel structures"],
    "cloud engineer": ["aws", "azure", "gcp", "cloud", "devops", "cloud computing", "infrastructure", "terraform", "kubernetes", "docker", "ci/cd", "cloud storage"],
    "content writer": ["seo", "writing", "blogs", "articles", "grammar", "copywriting", "content marketing", "editing", "content strategy", "creative writing", "research", "proofreading"],
    "cybersecurity specialist": ["network security", "firewall", "cybersecurity", "penetration testing", "encryption", "vulnerability", "incident response", "hacking", "network protocols", "threat hunting", "cyber attacks", "data protection"],
    "data analyst": ["data analysis", "dbms", "ms excel", "excel", "mysql", "sql", "tableau", "power bi", "python", "data cleaning", "data visualization", "predictive analytics"],
    "data engineer": ["etl", "big data", "spark", "hadoop", "data pipeline", "airflow", "data warehouse", "kafka", "nosql", "data integration", "python", "data processing"],
    "data scientist": ["python", "machine learning", "data analysis", "pandas", "numpy", "statistics", "scikit-learn", "deep learning", "visualization", "r", "tensorflow", "data mining"],
    "database": ["sql", "database", "mysql", "postgresql", "oracle", "queries", "data normalization", "relational databases", "data modeling", "sql server", "mongodb", "database management"],
    "database administrator": ["database", "backup", "sql", "monitoring", "recovery", "optimization", "db tuning", "disaster recovery", "performance tuning", "replication", "high availability", "data integrity"],
    "devops engineer": ["jenkins", "docker", "kubernetes", "ci/cd", "terraform", "aws", "ansible", "linux", "monitoring", "cloud computing", "scripting", "version control"],
    "digital marketer": ["seo", "sem", "google ads", "facebook ads", "social media", "analytics", "email marketing", "content marketing", "affiliate marketing", "digital strategy", "google analytics", "conversion optimization"],
    "dotnet developer": [".net", "c#", "asp.net", "mvc", "sql server", "entity framework", "visual studio", "azure", "web services", "javascript", "rest api", "linq"],
    "e-commerce specialist": ["shopify", "woocommerce", "ecommerce", "product listing", "seo", "digital marketing", "order management", "sales funnels", "payment gateways", "conversion rate optimization", "marketplace integration", "shopify apps"],
    "etl developer": ["etl", "informatica", "data warehouse", "ssrs", "ssis", "sql", "data transformation", "data integration", "oracle", "sql server", "data loading", "data pipeline"],
    "electrical engineering": ["circuit", "electrical", "power systems", "transformer", "voltage", "control systems", "electronics", "signal processing", "energy management", "renewable energy", "electrical design", "ac/dc circuits"],
    "game developer": ["unity", "unreal engine", "c#", "game design", "animation", "2d", "3d", "game programming", "ai programming", "game mechanics", "c++", "augmented reality"],
    "graphic designer": ["photoshop", "illustrator", "creativity", "branding", "coreldraw", "figma", "canva", "sketch", "logo design", "advertising", "web design", "visual design"],
    "hr": ["recruitment", "employee engagement", "payroll", "hr policies", "interviewing", "performance management", "onboarding", "labor laws", "employee relations", "talent acquisition", "benefits administration", "training and development"],
    "hr executive": ["onboarding", "hr operations", "leave management", "recruitment", "employee relations", "payroll", "hr policies", "hr analytics", "compliance", "talent management", "employee engagement", "team coordination"],
    "hadoop": ["hadoop", "mapreduce", "hive", "pig", "spark", "big data", "hdfs", "sqoop", "flume", "yarn", "kafka", "data lakes"],
    "health and fitness": ["nutrition", "fitness", "diet", "exercise", "training", "yoga", "health coaching", "personal training", "weight loss", "wellness", "strength training", "cardio"],
    "it support specialist": ["helpdesk", "it support", "troubleshooting", "network", "hardware", "service desk", "active directory", "windows", "itIL", "ticketing system", "remote desktop", "systems administration"],
    "java developer": ["java", "spring", "hibernate", "jsp", "maven", "spring boot", "j2ee", "java ee", "mysql", "sql", "rest api", "angular"],
    "mechanical engineer": ["solidworks", "autocad", "mechanical", "cad", "manufacturing", "thermal", "mechanical design", "mechanical testing", "material science", "finite element analysis", "3d modeling", "heat transfer"],
    "network engineer": ["networking", "routing", "switching", "ccna", "tcp/ip", "dns", "lan", "wan", "firewall", "vpn", "network security", "network protocols"],
    "network security engineer": ["firewall", "vpn", "security", "threat", "malware", "ids/ips", "ddos", "encryption", "network monitoring", "penetration testing", "incident response", "risk management"],
    "operations manager": ["operations", "management", "logistics", "planning", "supply chain", "team leadership", "strategic planning", "inventory management", "process improvement", "budget management", "project management", "performance metrics"],
    "pmo": ["project management", "pmo", "reporting", "ms project", "project planning", "stakeholder management", "risk management", "resource management", "agile", "scrum", "schedule management", "team collaboration"],
    "product manager": ["product management", "roadmap", "user stories", "agile", "feature prioritization", "stakeholder management", "product lifecycle", "market research", "scrum", "business analysis", "pricing strategy", "requirements gathering"],
    "project manager": ["project planning", "budget", "timeline", "resources", "stakeholder management", "team management", "risk management", "agile", "scrum", "project scheduling", "cost control", "scope management"],
    "python developer": ["python", "django", "flask", "scripting", "api", "web scraping", "fastapi", "sql", "pandas", "numpy", "automation", "testing"],
    "qa/test engineer": ["manual testing", "automation testing", "bug tracking", "test case", "jira", "quality assurance", "regression testing", "unit testing", "selenium", "load testing", "integration testing", "test scripts"],
    "robotics engineer": ["robotics", "embedded systems", "control systems", "microcontroller", "ros", "mechatronics", "arduino", "c++", "automation", "sensor integration", "motion control", "robot design"],
    "sap developer": ["sap", "abap", "sap hana", "erp", "sap modules", "sql", "database management", "data integration", "business workflow", "reporting", "user interface", "customization"],
    "seo specialist": ["seo", "keywords", "google analytics", "backlinks", "on-page seo", "off-page seo", "content strategy", "search engine marketing", "seo audit", "google search console", "rank tracking", "page speed optimization"],
    "sales": ["sales", "target", "lead generation", "crm", "negotiation", "customer service", "cold calling", "sales strategy", "account management", "client retention", "closing deals", "sales forecasting"],
    "software developer / full stack developer": ["frontend", "backend", "html", "css", "javascript", "react", "node", "express", "mongodb", "rest api", "typescript", "sql"],
    "solutions architect": ["architecture", "cloud", "design", "aws", "azure", "microservices", "docker", "kubernetes", "network design", "cloud migration", "system integration", "infrastructure design"],
    "systems administrator": ["linux", "windows server", "system admin", "bash", "powershell", "monitoring", "server maintenance", "networking", "cloud computing", "backup", "active directory", "virtualization"],
    "technical writer": ["documentation", "manual", "api docs", "technical writing", "guides", "user manuals", "help systems", "content management", "product documentation", "technical communication", "content writing", "technical specifications"],
    "testing": ["test case", "bug report", "manual testing", "automation", "unit testing", "selenium", "performance testing", "regression testing", "integration testing", "quality assurance", "test scripts", "load testing"],
    "ui/ux designer": ["figma", "adobe xd", "wireframe", "prototype", "usability", "ui design", "ux research", "user interface", "interaction design", "responsive design", "usability testing", "design systems"],
    "web developer": ["html", "css", "javascript", "react", "bootstrap", "responsive", "frontend", "backend", "node", "express", "api", "typescript"]
}
