job_keywords = {
    "ai/ml engineer": ["python", "machine learning", "tensorflow", "pytorch", "deep learning", "scikit-learn", "data science", "nlp", "opencv"],
    "ar/vr developer": ["unity", "unreal engine", "augmented reality", "virtual reality", "3d modeling", "blender", "c#"],
    "advocate": ["legal", "law", "case", "litigation", "drafting", "court", "contracts", "compliance"],
    "android/ios developer": ["android", "ios", "kotlin", "swift", "mobile development", "flutter", "react native", "xcode"],
    "arts": ["painting", "sculpture", "design", "drawing", "visual arts", "illustration", "fine arts"],
    "automation testing": ["selenium", "automation", "test scripts", "pytest", "testng", "robot framework", "ci/cd"],
    "blockchain": ["blockchain", "cryptocurrency", "ethereum", "smart contract", "solidity", "web3", "nfts", "defi"],
    "blockchain developer": ["solidity", "ethereum", "dapps", "smart contract", "hyperledger", "ganache", "truffle"],
    "business analyst": ["business analysis", "requirement gathering", "data analysis", "stakeholders", "user stories", "agile", "jira"],
    "business intelligence analyst": ["power bi", "tableau", "data visualization", "sql", "dashboard", "business objects"],
    "civil engineer": ["autocad", "construction", "site engineer", "project management", "structural", "estimation"],
    "cloud engineer": ["aws", "azure", "gcp", "cloud", "devops", "cloud computing", "infrastructure", "terraform"],
    "content writer": ["seo", "writing", "blogs", "articles", "grammar", "copywriting", "content marketing"],
    "cybersecurity specialist": ["network security", "firewall", "cybersecurity", "penetration testing", "encryption", "vulnerability"],
    "data analyst": ["data analysis", "dbms", "ms excel", "excel", "mysql", "sql", "tableau", "power bi", "python"],
    "data engineer": ["etl", "big data", "spark", "hadoop", "data pipeline", "airflow", "data warehouse", "kafka"],
    "data scientist": ["python", "machine learning", "data analysis", "pandas", "numpy", "statistics", "scikit-learn", "deep learning", "visualization"],
    "database": ["sql", "database", "mysql", "postgresql", "oracle", "queries"],
    "database administrator": ["database", "backup", "sql", "monitoring", "recovery", "optimization", "db tuning"],
    "devops engineer": ["jenkins", "docker", "kubernetes", "ci/cd", "terraform", "aws", "ansible", "linux", "monitoring"],
    "digital marketer": ["seo", "sem", "google ads", "facebook ads", "social media", "analytics", "email marketing"],
    "dotnet developer": [".net", "c#", "asp.net", "mvc", "sql server", "entity framework", "visual studio"],
    "e-commerce specialist": ["shopify", "woocommerce", "ecommerce", "product listing", "seo", "digital marketing"],
    "etl developer": ["etl", "informatica", "data warehouse", "ssrs", "ssis", "sql", "data transformation"],
    "electrical engineering": ["circuit", "electrical", "power systems", "transformer", "voltage", "control systems"],
    "game developer": ["unity", "unreal engine", "c#", "game design", "animation", "2d", "3d"],
    "graphic designer": ["photoshop", "illustrator", "creativity", "branding", "coreldraw", "figma", "canva"],
    "hr": ["recruitment", "employee engagement", "payroll", "hr policies", "interviewing"],
    "hr executive": ["onboarding", "hr operations", "leave management", "recruitment", "employee relations"],
    "hadoop": ["hadoop", "mapreduce", "hive", "pig", "spark", "big data"],
    "health and fitness": ["nutrition", "fitness", "diet", "exercise", "training", "yoga", "health coaching"],
    "it support specialist": ["helpdesk", "it support", "troubleshooting", "network", "hardware", "service desk"],
    "java developer": ["java", "spring", "hibernate", "jsp", "maven", "spring boot", "j2ee"],
    "mechanical engineer": ["solidworks", "autocad", "mechanical", "cad", "manufacturing", "thermal"],
    "network engineer": ["networking", "routing", "switching", "ccna", "tcp/ip", "dns", "lan", "wan"],
    "network security engineer": ["firewall", "vpn", "security", "threat", "malware", "ids/ips"],
    "operations manager": ["operations", "management", "logistics", "planning", "supply chain"],
    "pmo": ["project management", "pmo", "reporting", "ms project", "project planning"],
    "product manager": ["product management", "roadmap", "user stories", "agile", "feature prioritization"],
    "project manager": ["project planning", "budget", "timeline", "resources", "stakeholder management"],
    "python developer": ["python", "django", "flask", "scripting", "api", "web scraping", "fastapi"],
    "qa/test engineer": ["manual testing", "automation testing", "bug tracking", "test case", "jira", "quality assurance"],
    "robotics engineer": ["robotics", "embedded systems", "control systems", "microcontroller", "ros"],
    "sap developer": ["sap", "abap", "sap hana", "erp", "sap modules"],
    "seo specialist": ["seo", "keywords", "google analytics", "backlinks", "on-page seo", "off-page seo"],
    "sales": ["sales", "target", "lead generation", "crm", "negotiation"],
    "software developer / full stack developer": ["frontend", "backend", "html", "css", "javascript", "react", "node", "express", "mongodb", "rest api"],
    "solutions architect": ["architecture", "cloud", "design", "aws", "azure", "microservices"],
    "systems administrator": ["linux", "windows server", "system admin", "bash", "powershell", "monitoring"],
    "technical writer": ["documentation", "manual", "api docs", "technical writing", "guides"],
    "testing": ["test case", "bug report", "manual testing", "automation", "unit testing"],
    "ui/ux designer": ["figma", "adobe xd", "wireframe", "prototype", "usability", "ui design", "ux research"],
    "web developer": ["html", "css", "javascript", "react", "bootstrap", "responsive", "frontend", "backend", "node", "express", "api"]
}
